// we import the types to re-export them inside types.
import {
    enumeration,
    model,
    compose,
    composeGenericForwarding,
    custom,
    reference,
    safeReference,
    union,
    unionGenericForwarding,
    optional,
    literal,
    maybe,
    maybeNull,
    refinement,
    string,
    boolean,
    number,
    integer,
    DatePrimitive,
    map,
    array,
    frozen,
    identifier,
    identifierNumber,
    late,
    undefinedType,
    nullType,
    snapshotProcessor
} from "../internal"

export const types = {
    enumeration,
    model,
    compose,
    composeGenericForwarding,
    custom,
    reference,
    safeReference,
    union,
    unionGenericForwarding,
    optional,
    literal,
    maybe,
    maybeNull,
    refinement,
    string,
    boolean,
    number,
    integer,
    Date: DatePrimitive,
    map,
    array,
    frozen,
    identifier,
    identifierNumber,
    late,
    undefined: undefinedType,
    null: nullType,
    snapshotProcessor
}
